# Generated by Django 4.1.2 on 2022-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photo_created_at_alter_photo_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='albumId',
            field=models.IntegerField(),
        ),
    ]
