# Generated by Django 4.1.2 on 2022-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_photo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
