# Generated by Django 4.1.2 on 2022-10-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_photo_color_alter_photo_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.CharField(default='aasda', max_length=1000),
            preserve_default=False,
        ),
    ]
